keybind = alt+f=csi:24~
keybind = alt+n=set_tab_title:__WS_NEW_SESSION__
keybind = chain=csi:24~
keybind = alt+w=text:__WS_ARCHIVE_CURRENT_SESSION__
keybind = chain=csi:24~
keybind = alt+r=esc:r
keybind = alt+enter=csi:13;2u
confirm-close-surface = false
